### PR TITLE
not a fan of thanos

### PR DESCRIPTION
**Pull request by ganeshi4u**

### CODE REVIEW

**Comment by ATechnoHazard** [comment]
Nice double imports you got there....

**Comment by ganeshi4u** [comment]
aye lawde that was a joke, technically it doesn't work!

**Comment by PaulSonOfLars** [comment]
Why is this a good idea for a PR? Give an explanation.

**Comment by mohancm** [comment]
😆😆😆

**Comment by gargakshit** [comment]
Lul

**Pull request closed without merging**
